HPAuthenticate/HPAuthenticate/Controllers/ReportingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HPEntities;
using Newtonsoft.Json.Linq;
using HPEntities.Dalcs;
using HPEntities.Entities.JsonClasses;
using Newtonsoft.Json;
using System.Text.RegularExpressions;
using libMatt.Formatters;
using HPEntities.Entities;
using libMatt.Converters;
using System.Configuration;
using System.Web.Routing;
using HPEntities.Exceptions;
using libMatt.Linq;
using HPAuthenticate.Helpers;

namespace HPAuthenticate.Controllers {
	public class ReportingController : ApplicationController {

		public class ReportingViewModel {
			public string pageState { get; set; }
			/// <summary>
			/// Dictionary&lt;int, Dictionary&lt;int, double&gt;&gt;
			/// { fromUnitId: { toUnitId: factor, toUnitId: factor, ... } }
			/// 
			/// </summary>
			public string unitConversionFactors;

			/// <summary>
			/// { CountyID: { 'mcf':1.123456, 'kwh':0.02235 }, ... }
			/// </summary>
			public string meterUnitConversionFactors;
		}

		public class DeploymentFilter : ActionFilterAttribute {
			public override void OnActionExecuting(ActionExecutingContext filterContext) {
				if (!ConfigurationManager.AppSettings["is_reporting_deployed"].ToBoolean()) {
					filterContext.Result = new RedirectToRouteResult(
						new RouteValueDictionary { { "Controller", "User" }, { "Action", "Details" } }
					);
				}
				base.OnActionExecuting(filterContext);
			}
		}



		protected int CurrentReportingYear = DateTime.Now.Year;
		protected bool IsReportingAllowed = false;


		public ReportingController() {
			var currentDate = DateTime.Now;

			// Only allow reporting from 15 Dec - 1 Jun, and if 
			// current date is in Jan-Mar, the reporting year is "last" year.
			if ((currentDate.Month == 12 && currentDate.Day >= 15)
				|| (currentDate.Month < 6)
				|| (currentDate.Month == 6 && currentDate.Day <= 1)) {
				IsReportingAllowed = true;
				CurrentReportingYear = (currentDate.Month > 6) ? currentDate.Year : currentDate.Year - 1;
			} else {
				IsReportingAllowed = false;
			}

		}


		#region CA object creation, persistence, "cache invalidation"

		/// <summary>
		/// This method populates all properties that should be refreshed on every page
		/// load, i.e. not using existing stored JSON state.
		/// </summary>
		/// <param name="ca"></param>
		/// <returns></returns>
		protected JsonContiguousAcres PopulateNonPersistentProperties(JsonContiguousAcres ca) {
			throw new NotImplementedException();
		}

		#endregion


		/// <summary>
		/// Creates a dynamic object representing the page state.
		/// This method will attempt to load and deserialize JSON
		/// from the database if it exists for this user (updating
		/// relevant properties appropriately), and if no existing
		/// JSON exists will construct a new object with which the
		/// user can report water usage.
		/// </summary>
		/// <returns></returns>
		protected dynamic GetPageStateJson(User user) {
			// Only update the _current_ reporting year or unsubmitted 
			var pageStateJson = new ReportingDalc().GetReportingSummary(user.IsAdmin ? (user.ActingAsUserId ?? user.Id) : user.Id);
			

			ReportingSummary pageState = null;
			try {
				pageState = JsonConvert.DeserializeObject<ReportingSummary>(pageStateJson);
			} catch (Exception ex) {
				// There was a problem deserializing.
				// TODO: Notify user, possibly admins!
				throw;
			}
			if (pageState == null) {
				pageState = new ReportingSummary();
			}

			/// Returns the volume (Item1) and a bool indicating whether rollover occurred (Item2)
			/// Args: meterInstallationId, meterreadings
			Func<int, IEnumerable<JsonMeterReading>, Tuple<int, bool>> calculateVolume = (meterInstallationId, readings) => {
				double runningTotal = 0d;
				if (readings.Count() == 0) {
					return new Tuple<int, bool>((int)runningTotal, false);
				}
				bool rolledOver = false;
				var prevReading = readings.First();
				foreach (var currentReading in readings.Skip(1)) {
					double delta = 0;
					if (currentReading.reading.GetValueOrDefault() < prevReading.reading.GetValueOrDefault()) {
						// Rollover occurred
						rolledOver = true;
						// Retrieve the rollover value for this meter installation
						var rollover = new MeterDalc().GetMeterInstallations(meterInstallationId).First().RolloverValue;
						delta = (rollover - prevReading.reading.Value) + currentReading.reading.Value;
					} else {
						delta = currentReading.reading.GetValueOrDefault() - prevReading.reading.GetValueOrDefault();
					}

					runningTotal += delta * (prevReading.rate.HasValue ? prevReading.rate.Value : 1);

					prevReading = currentReading;
				}

				return new Tuple<int, bool>((int)runningTotal, rolledOver);
			};

			// Only show Approved CAs unless the user is an admin
			var contigAcres = new GisDalc().GetContiguousAcres(user, true).Where(ca => user.IsAdmin || ca.IsApproved);


			// Key: CA ID, Value: well ids
			var wellIds = new Dictionary<int, HashSet<int>>();
			Dictionary<int, ContiguousAcres> validAcres = new Dictionary<int, ContiguousAcres>();

			// There may be load errors that got persisted from a previous page load, but we
			// only want to show current ones so clear the list.
			pageState.loadErrors.Clear();

			if (contigAcres.Count() > 0) { // Only create the service if contigAcres has stuff, because SOAP takes time
				var service = new GisServiceSoapClient();
				foreach (var ca in contigAcres) {
                    string result = "";
                    // This call is prone to failure whenever the GIS service is down.
                    try {
                        result = service.GetWellIDsByCA(ca.OBJECTID);
                    } catch (Exception ex) {
                        pageState.loadErrors.Add("Unable to load well associations for any CAs: the GIS service appears to be down!");
                    }
					try {
						int[] ids = JsonConvert.DeserializeObject<int[]>(result.Trim('{', '}'));
						wellIds[ca.caID] = new HashSet<int>(ids);
						validAcres[ca.caID] = ca;
					} catch (JsonException ex) {
						pageState.loadErrors.Add("Error loading CA ID " + ca.caID + ": " + ex.Message + " Service response: " + result);
					}

				}
			}

			var mdalc = new MeterDalc();
			var rptgDalc = new ReportingDalc();

			var wellDalc = new WellDalc();
			var wells = wellDalc.GetWells(wellIds.SelectMany(x => x.Value).ToArray());
			var meterInstallations = mdalc.GetMeterInstallations(wells.SelectMany(x => x.MeterInstallationIds).ToArray()).GroupBy(x => x.Id).Select(x => x.First()).ToDictionary(x => x.Id, x => x);
			// In addition to the wells retrieved by the spatial query, we also need to
			// retrieve wells attached to the meters on that initial set.
			wells = wells.Concat(wellDalc.GetWellsByMeterInstallationIds(meterInstallations.Select(x => x.Key).ToArray()))
							.Distinct((a,b) => a.WellId == b.WellId);
						

			Func<int, Dictionary<int, JsonBankedWaterRecord>> getBankedWaterTable = caId => {
				return rptgDalc.GetHistoricalBankedWater(caId).ToDictionary(x => x.year, x => x);
			};

			// func to populate a JsonCA in the current reporting year
			Func<ContiguousAcres, JsonContiguousAcres> createNewJsonCA = ca => {
				ca.Wells = wellDalc.GetWells(wellIds[ca.caID].ToArray()).ToArray();
				var reportedVolumes = mdalc.GetReportedVolumeGallons(ca.Wells.SelectMany(w => w.MeterInstallationIds), ca.caID, CurrentReportingYear);
				JsonContiguousAcres ret = new JsonContiguousAcres(ca, CurrentReportingYear);
				ReportedVolume rvol;
				ret.meterReadings = new Dictionary<int, JsonMeterReadingContainer>();
				MeterInstallation meter = null;

				foreach (var miid in ret.wells.SelectMany(x => x.meterInstallationIds).Distinct()) {
					meterInstallations.TryGetValue(miid, out meter);
					var container = new JsonMeterReadingContainer() {
						meterInstallationId = miid,
						calculatedVolumeGallons = reportedVolumes.TryGetValue(miid, out rvol) ? rvol.CalculatedVolumeGallons : 0,
						acceptCalculation = rvol == null || !rvol.UserRevisedVolumeUnitId.HasValue,
						userRevisedVolume = rvol != null && rvol.UserRevisedVolume.HasValue ? rvol.UserRevisedVolume.Value : 0,
                        userRevisedVolumeUnitId = rvol != null && rvol.UserRevisedVolumeUnitId.HasValue ? rvol.UserRevisedVolumeUnitId.Value : new int?(),
						totalVolumeAcreInches = 0,
						isNozzlePackage = meter != null ? meter.MeterType.Description().ToLower() == "nozzle package" : false,
                        isElectric = meter != null ? meter.MeterType.Description().ToLower() == "electric" : false,
                        isNaturalGas =  meter != null ? meter.MeterType.Description().ToLower() == "natural gas" : false,
                        isThirdParty = meter != null ? meter.MeterType.Description().ToLower() == "bizarro-meter" : false,
                        depthToRedbed = -99999,
                        //squeezeValue = 0,
						unitId = meter != null ? meter.UnitId : null,
						county = meter != null ? meter.County : "",
						rolloverValue = meter != null ? meter.RolloverValue : 0,
						countyId = meter != null ? meter.CountyId : -1,
						meterType = meter != null ? meter.MeterType.Description() : "",
						nonStandardUnits = meter != null && meter.MeterType != HPEntities.Entities.Enums.MeterType.standard ? new MeterDalc().GetUnits(meter.MeterType).Description() : "",
						meterMultiplier = meter.Multiplier != 0 ? meter.Multiplier : 1.0d // Make sure multiplier is not 0. NULL value is already converted to 1.0d in Dalc
					};

                    // Add depth to redbed if the meter is of 1) natural gas or 2) electric
                    if (container.isNaturalGas || container.isElectric)
                    {

HPAuthenticate/HPAuthenticate/Views/Shared/CreateUser.cshtml
@model HPAuthenticate.ViewModels.UserViewModel
@using HPAuthenticate.ViewModels
@using HPAuthenticate.Helpers


@{
    ViewBag.Title = "Create Account";
}

@section footer_scripts {
	<script src="@Url.Script("jquery.validate.js")"></script>
	<script src="@Url.Script("jquery.validate.unobtrusive.js")"></script>
}


<h2>Create Account</h2>

<p>Fields marked with an asterisk (*) are required.</p>

@using (Html.BeginForm()) {
	@Html.ValidationSummary(false, "Unable to create account; please correct the errors and try again.")
	<dl class="form">
		<dt>
			@Html.LabelFor(m => m.User.Email)@if (!(Model is AdminCreateUserViewModel)) {<text>*</text>}
		</dt>
		<dd>
			@Html.TextBoxFor(m => m.User.Email)
			<br /><span id='email_availability_status'></span><br />
			@Html.ValidationMessageFor(m => m.User.Email)
		</dd>

		@if (!(Model is AdminCreateUserViewModel)) {
			<text>
				<dt>
					@Html.LabelFor(m => m.Password)*
				</dt>
				<dd>
					@Html.PasswordFor(m => m.Password)
					<span class='hint'>Must be at least 6 characters.</span><br />
					@Html.ValidationMessageFor(m => m.Password)
				</dd>
				<dt>
					@Html.LabelFor(m => m.PasswordConfirmation)*
				</dt>
				<dd>
					@Html.PasswordFor(m => m.PasswordConfirmation)<br />
					@Html.ValidationMessageFor(m => m.PasswordConfirmation)
				</dd>
			</text>
		}


		<dt>
			@Html.LabelFor(m => m.User.LastNameOrCompany)*
		</dt>
		<dd>
			@Html.TextBoxFor(m => m.User.LastNameOrCompany)<br />
			@Html.ValidationMessageFor(m => m.User.LastNameOrCompany)
		</dd>

		<dt>
			@Html.LabelFor(m => m.User.FirstName)
		</dt>
		<dd>
			@Html.TextBoxFor(m => m.User.FirstName)<br />
			@Html.ValidationMessageFor(m => m.User.FirstName)
		</dd>

		<dt>
			@Html.LabelFor(m => m.User.MiddleInitial)
		</dt>
		<dd>
			@Html.TextBoxFor(m => m.User.MiddleInitial)<br />
			@Html.ValidationMessageFor(m => m.User.MiddleInitial)
		</dd>


		<dt>
			@Html.LabelFor(m => m.User.CourtesyTitleId)
		</dt>
		<dd>
			@Html.DropDownListFor(m => m.User.CourtesyTitleId, Model.AvailableCourtesyTitles)<br />
			@Html.ValidationMessageFor(m => m.User.CourtesyTitleId)
		</dd>

		<dt>
			@Html.LabelFor(m => m.User.Suffix)
		</dt>
		<dd>
			@Html.TextBoxFor(m => m.User.Suffix)<br />
			@Html.ValidationMessageFor(m => m.User.Suffix)
		</dd>

		<dt>
			@Html.LabelFor(m => m.User.PreferredName)
		</dt>
		<dd>
			@Html.TextBoxFor(m => m.User.PreferredName)<br />
			@Html.ValidationMessageFor(m => m.User.PreferredName)
		</dd>



		<dt>
			@Html.LabelFor(m => m.Address)*
		</dt>
		<dd>
			@Html.TextBoxFor(m => m.Address)<br />
			@Html.ValidationMessageFor(m => m.Address)
		</dd>

		<dt>
			@Html.LabelFor(m => m.City)*
		</dt>
		<dd>
			@Html.TextBoxFor(m => m.City)<br />
			@Html.ValidationMessageFor(m => m.City)
		</dd>

		<dt>
			@Html.LabelFor(m => m.State)*
		</dt>
		<dd>
			@Html.DropDownListFor(m => m.State, HPAuthenticate.ViewModels.UserViewModel.AvailableStates)<br />
			@Html.ValidationMessageFor(m => m.State)
		</dd>			


		<dt>
			@Html.LabelFor(m => m.PostalCode)*
		</dt>
		<dd>
			@Html.TextBoxFor(m => m.PostalCode)<br />
			@Html.ValidationMessageFor(m => m.PostalCode)
		</dd>

		<dt>
			Phone number(s)*<br />
			<span class='hint'>E.g. (806) 762-0181 x123</span><br />
			<span class='hint'>Provide at least one number</span>
		</dt>
		<dd>
			@Html.ValidationMessage("Number")
			@Html.ValidationMessage("Extension")
			@Html.Partial("_PhoneNumberForm", Model)

			@Html.ValidationMessageFor(m => m.User.PhoneNumbers)
		</dd>		

		<dt></dt>
		<dd>
			@Html.Hidden("x_user_id", Request["x_user_id"], new { id = "x_user_id" })
			<input type="submit" value="Create account"></input>
		</dd>
	</dl>
	<div class="clear"></div>
}

<script type="text/javascript">

	$(document).ready(function () {
		$('#User_LastNameOrCompany').autocomplete({
			source: function(request, response) {
				$.ajax(
					"@Url.Action("FindClients", "User")",
					{
						type: "POST",
						data: {
							term: request.term
						},
						success: function(data, textStatus, jqXHR) {
							if (data.length == 0) {
								data.push({DisplayName:'No matches found', DisplayAddress:['a new user record will be created'], selectable: false});
							}
							response(data);
						},
						error: function(jqXHR, textStatus, errorThrown) {
							// Swallow it.
						},
						complete: function(jqXHR, textStatus) {

						}
					}
				);
			},
			select: function(event, ui) {
				if (ui.item.selectable === false) {
					return false;
				}
				// Autofill the remaining form fields.
				$('#User_LastNameOrCompany').val(ui.item.LastName);
				$('#User_MiddleInitial').val(ui.item.MiddleInitial);
				$('#User_FirstName').val(ui.item.FirstName);
				$('#User_Suffix').val(ui.item.Suffix);
				$('#User_PreferredName').val(ui.item.PreferredName);
				$('#Address').val(ui.item.Address);
				$('#City').val(ui.item.City);
				$('#State').val(ui.item.State);
				$('#PostalCode').val(ui.item.PostalCode);
				$('#x_user_id').val(ui.item.UserId);

				for (var i = 0; i < ui.item.PhoneNumbers.length; i++) {
					addPhoneNumber(ui.item.PhoneNumbers[i].PhoneTypeId, ui.item.PhoneNumbers[i].Number);
				}

				return false;
			}
		}).data("autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a>" + item.DisplayName + "<br><span>" + item.DisplayAddress + "</span></a>")
				.appendTo(ul);
		};

		// Check availability of email address when entered
		$('#User_Email').blur(function() {
			var txtbox = $('#User_Email');
			if (txtbox.val() && txtbox.valid()) {
				$.ajax(
					"@Url.Action("IsEmailAvailable", "User")",
					{
						type:"POST",
						data: { email: txtbox.val() },
						success: function(data, textStatus, jqXHR) {
							if (data === true) {
								$('#email_availability_status').removeClass('error').addClass('success').text('Email address available').show();
							} else {
								$('#email_availability_status').removeClass('success').addClass('error').text('Email address already taken! ').append('<a href="@Url.Action("ResetPassword", "Session")">Forgot password?</a>').show();
							}
						}
					}
				);
			} else {
				$('#email_availability_status').hide();
			}

		}).keydown(function() {
			$('#email_availability_status').empty().hide();
		});

	});

</script>

HPAuthenticate/HPAuthenticate/Views/Shared/_ActAsSelector.cshtml
@using HPAuthenticate.Helpers

@using (@Html.BeginForm("ActAs", "User")) {

	<div id='act_as_info'>
		<p class='icon uid'>Logged in as @ViewBag.CurrentUsername.</p>
		@if (ViewBag.IsAdmin) {
			<div class='icon actas'>
				@if (ViewBag.Acting) {
					<text>
						<span id='act_as_descriptor' class='img_container'>
							Acting as <a href='#' id='act_as_link'>@ViewBag.ActingUser.DisplayName <img src='@Url.Image("xfn-friend.png")' alt='' title='Change user' /></a>
							<input type='image' src='@Url.Image("prohibition-button.png")' value='1' name='cancel_act_as' alt='Revert' title='Revert to your own account (stop acting)' />
						</span>
					</text>
				} else {
					<text>
						<span id='act_as_descriptor'><a href='#' id='act_as_link'>Act as...</a></span>
					</text>
				}

				<div id='act_as_selector' style="display:none;">
						@Html.Hidden("return_uri", Request.Url.ToString())
						@Html.TextBox("act_as_name")
						@Html.Hidden("act_as_user_id")
						<a href='#' id='cancel_act_as'><img src='@Url.Image("cross.png")' alt="Cancel" /></a>
				</div>
			</div>
		}
	</div>
}

<script type='text/javascript'>

	$(document).ready(function () {
		$('#act_as_link').live('click', function() {
			$('#act_as_descriptor').hide();
			$('#act_as_selector').show().find('#act_as_name').val('').focus();
			return false;
		});

		function showDescriptor() {
			$('#act_as_selector').hide();
			$('#act_as_descriptor').show();
		}

		$('#cancel_act_as').click(showDescriptor);
		$('#act_as_name').blur(showDescriptor);

		$('#act_as_name').autocomplete({
			source: function (request, response) {
				$.ajax(
					"@Url.Action("FindClientsByNameOrEmail", "User")",
					{
						type: "POST",
						data: {
							term: request.term
						},
						success: function(data, textStatus, jqXHR) {
							if (data.length == 0) {
								data.push({DisplayName:'No matching users found',DisplayAddress:[''],selectable:false});
							}
							response(data);
						},
						error: function(jqXHR, textStatus, errorThrown) {
							if (console && console.debug) {
								console.debug(jqXHR, textStatus, errorThrown);
							}
							$('#act_as_name_status').text(errorThrown);
						}
					}
				)
			},
			select: function(event, ui) {
				if (ui.item.selectable === false) {
					return false;
				}

				$('#act_as_user_id').val(ui.item.UserId);
				$('#act_as_name').val(ui.item.DisplayName).parents('form').submit();
				
			}
		}).data("autocomplete")._renderItem = function(ul, item) {
			return $("<li></li>")
				.data("item.autocomplete", item)
				.append("<a>" + item.DisplayName + "<br><span>" + item.DisplayAddress + "<br />" + item.Email + "</span></a>")
				.appendTo(ul);
		};
	});

</script>

HPAuthenticate/HPAuthenticate/Views/Shared/_Layout.cshtml
@using HPAuthenticate.Helpers

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" ></meta>
    <title>@ViewBag.Title</title>
	<link href="@Url.Stylesheet("themes/base/jquery.ui.base.css")" rel="stylesheet" type="text/css"></link>
	<link href="@Url.Stylesheet("themes/base/jquery.ui.theme.css")" rel="stylesheet" type="text/css"></link>
	<link href="@Url.Stylesheet("themes/base/jquery.ui.autocomplete.css")" rel="stylesheet" type="text/css"></link>
	<link href="@Url.Stylesheet("Site.css")" rel="stylesheet" type="text/css"></link>
	<script type='text/javascript'>
		if (!console) {
			var console = {
				log: function () { },
				debug: function () { },
				warn: function() { }
			}
		}
	</script>
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-36982226-1']);
        _gaq.push(['_setDomainName', 'hpwd.com']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
    <script src="@Url.Script("modernizr-1.7.min.js")" type="text/javascript"></script>
	<script src="@Url.Script("jquery.tipsy.pack.js")" type="text/javascript"></script>
	<script src="@Url.Script("json2.pack.js")" type="text/javascript"></script>
	<script src="@Url.Script("app.js")" type="text/javascript"></script>

	<script type='text/javascript'>

		$(document).ready(function () {
			$('#link_reporting').tipsy({ gravity: 'n' });
		});
	</script>
	@RenderSection("header_scripts", false)
</head>
<body>
    <div class="page">
        <header>
			<h1>
				<img src="@Url.Image("hpwdtop3.jpg")" alt=''></img>
				<a href="@Url.Action("Index", "Home")">
					<img src='@Url.Image("hpwdbanner.gif")' alt='High Plains Conservation District'></img>
				</a>
			</h1>
            <nav>
	
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
	@if (ViewBag.CurrentUser == null) {
	                <li>@Html.ActionLink("Sign up", "Create", "User")</li>
					<li>@Html.ActionLink("Login", "Login", "Session")</li>
 } else {
					<li>@Html.ActionLink("My Account", "Details", "User")</li>
@*<<<<<<< HEAD
	 //if (ViewBag.CurrentUser.Properties.Count > 0) {
=======
>>>>>>> 5b5d5bf7bee0288a4b8030644d692085ec5e8c2b*@
					<li><a id='link_reporting' title="Report a meter installation or an alternate method" href="@Url.Content("/hpuwcd/index.html?config=config-menu.xml")">Reporting</a></li>
					<li>@Html.ActionLink("Annual Report", "Index", "Reporting")</li>
@*<<<<<<< HEAD
		 }
	 //}
=======
>>>>>>> 5b5d5bf7bee0288a4b8030644d692085ec5e8c2b*@
					<li>@Html.ActionLink("Logout", "Logout", "Session")</li>
 }
					@if (ViewBag.IsAdmin != null && ViewBag.IsAdmin) {
                        
						<li>@Html.ActionLink("Admin", "Index", "Admin")</li>
					}
					<li>@Html.ActionLink("Help", "Help", "Home")</li>
                </ul>

				<div class='clear'></div>

            </nav>
        </header>
        <section id="main">
			@if (ViewBag.IsAdmin != null && ViewBag.IsAdmin)
   {
				@Html.Partial("_ActAsSelector")
			} else if (!string.IsNullOrEmpty(ViewBag.CurrentUsername)) {
				<div id='login_indicator'>
					@System.Web.Mvc.Html.LinkExtensions.ActionLink(Html, ViewBag.CurrentUsername.ToString(), "Details", "User")
				</div>
			}

			<div id='flash'></div>
			@Flash.FlashMessage(TempData)

            @RenderBody()
        </section>
        <footer>
            @if (ViewBag.IsAdmin) {
                <div id="release_version">
                    Release version:
                    @Html.Raw("<a href='https://github.com/jiadreamran/HPAuthenticate/commit/" + ViewBag.CommitHash + "'>" + ViewBag.CommitHash + "</a>")
                 </div>
                }
			<a href="http://hpwd.com/home.asp">Home</a> |
			<a href="http://hpwd.com/about_us.asp">About Us</a> |
			<a href="http://hpwd.com/the_ogallala.asp">Ogallala</a> |
			<a href="http://hpwd.com/programs/programs.asp">Programs &amp; Activities</a> |
			<a href="http://hpwd.com/news/news.asp">News &amp; Info</a><br>

			<a href="http://hpwd.com/Conversation/conservmenu.asp">Conservation Tips</a> |
			<a href="http://hpwd.com/links.asp">Water Links</a> |
			<a href="http://hpwd.com/downloads/downloads.asp">Downloads</a> |
			<a href="http://hpwd.com/contact_us.asp">Contact Us</a> |
			<a href="http://hpwd.com/contact/mailform.asp?qsMailType=Survey&qsEmailTo=Info@hpwd.com">Feedback</a>
        </footer>
    </div>

	@RenderSection("footer_scripts", false)
</body>
</html>

HPAuthenticate/HPAuthenticate/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}

HPAuthenticate/HPAuthenticate/Views/Shared/_LoginForm.cshtml
	<dl class="form">
		<dt>@Html.Label("Email")</dt>
		<dd>@Html.TextBox("email")</dd>

		<dt>@Html.Label("Password")</dt>
		<dd>@Html.Password("password")</dd>

		<dt></dt>
		<dd>
			<label>@Html.CheckBox("remember_me", true) Remember me</label>
		</dd>

		<dt></dt>
		<dd><input type="submit" value="Login"></input></dd>

		<dt></dt>
		<dd>
			@Html.ActionLink("Forgot password?", "ResetPassword", "Session")
		</dd>
	</dl>



	<div class="clear"></div>

	